### ISSUE TITLE
targets mode issue

### ISSUE THREAD

**Issue by elangelo** [3F/vsSolutionBuildEvent#35]
I'm using the Targets Mode to start a powershell script that does the stuff i want (copying config files around, stopping (prebuild) and starting (postbuild) services.

.targets lookse like:
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Target Name="Init">
        <!--dirty hack to add a space inside the argument, otherwise the argument is not properly parsed, Trim it in the script!!-->
        <Exec Command="C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -File &quot;$(SolutionDir)/Prebuild.ps1&quot; &quot;$(SolutionDir) &quot; &quot;$(TargetDir) &quot;" />
</Target>
</Project>
```

The powershell scripts only use standard Powershell cmdlets (Write-Output, Copy-Item, Stop-Service and Start-Service)

This used to work very well with vssbe 0.12.7 but with 0.12.9 this seemed to stop working.
The scripts get executed as expected but it looks like after the postbuild target has run, visual studio waits for some output of vssbe as visual studio is completely unresponsive.

**Comment by 3F** [comment]
Thanks for report,

I think this problem was solved at the same time with #34

Can you check latest binaries ? [see build-175](https://ci.appveyor.com/project/3Fs/vssolutionbuildevent/history): https://ci.appveyor.com/project/3Fs/vssolutionbuildevent/build/build-175/artifacts

For details: in #34 I also changed block with ErrorListProvider (Error List VS pane), because I saw strange deadlock for NLog.

**Comment by elangelo** [comment]
indeed that seems to fix the issue.
Gr,S.

**Comment by 3F** [comment]
Good !

It planned for v0.12.10

Please note: I do not recommend use debug versions above in production, but you can also build it manually if you need this immediately.

* Inside IDE with vsSBE or use [build/](https://github.com/3F/vsSolutionBuildEvent/tree/master/build)
    * details [here](http://vssbe.r-eg.net/doc/Dev/How-to-build/)
