### ISSUE TITLE
Interrupt a build with pre-build event script

### ISSUE THREAD

**Issue by ghost** [3F/vsSolutionBuildEvent#37]
I have a windows batch script and also a powershelI script, both running during a solution pre-build event. These scripts are responsible for checking some pre-conditions before proceeding with the solution build.
In some cases were these conditions are not satisfied, I would like to stop/block the build process and show an error on Visual Studio's Output Window.
I've been trying hard to find the right scripting commands for vsSolutionBuildEvent, but no success yet... Would you please tell me if that is possible to achieve, and which commands/settings should I use for that?

**Comment by 3F** [comment]
## Example 1

The easy way to work with VS Output window through [SBE-Scripts](http://vssbe.r-eg.net/doc/Scripts/SBE-Scripts/)

something like this:
```java
#[( $(MyScriptErr) != "" )
{ 
  #[Build cancel = true]
  
  #[OWP item("My Item").writeLine(true): 
        any message data. 
        Error: #[$(MyScriptErr)] 
   ]
}]
```

where:

* `$(MyScriptErr) != ""` to check that 'MyScriptErr' (User-Variable and/or MSBuild property) does not contain any error
    * To manage it, for example: you can call your external script and capture STDOUT as result, e.g.:
    
```Java
#[var MyScriptErr = #[File sout("fname.exe", "args")]]
```

to capture also STDERR you can try this:

```java
#[try
{ 
    #[var test1 = #[File sout("preBuild.bat")]]
}
catch(err, msg)
{
    #[var test1 = #[$(msg)]]
}]
```

* `#[Build cancel = true]` - To immediately cancel the build task if it's possible. *You can also stop it via EnvDTE or exec command etc.*
* `#[OWP item("My Item")...` - use item "My Item" from VS Output window (write message but initially create it if not exists -the `true` first arg)

components here: http://vssbe.r-eg.net/doc/Scripts/SBE-Scripts/Components/

## Example 2

The other easy way - [Targets Mode](http://vssbe.r-eg.net/doc/Modes/Targets/).

something like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

    <Target Name="Init">
        <Exec Command="preBuild.bat &quot;arg1&quot; &quot;arg2&quot;" />
        <CallTarget Targets="StopAndErr" />
    </Target>
    
    <Target Name="StopAndErr">
        <Error  Condition="'$(MyScriptErr)'!=''" 
                Text="any message data. Error: '$(MyScriptErr)'" />
    </Target>
    
</Project>
```

Where `Exec task` should call your external script and `Error task` should stop your build and write into Output window about problem. See MSDN.

## Example 3

The other advanced way - [C# Mode](http://vssbe.r-eg.net/doc/Modes/CSharp/):

```csharp
public static int Init(ICommand cmd, ISolutionEvent evt)
{
    ...  
    IOW pane = cmd.Env.OutputWindowPane;
    pane.getByName("Custom Name", true).OutputString(" Hello World! ");
}
```
You can easy get access to EnvDTE (DTE2 & DTE), Microsoft.Build.Evaluation.Project etc. in a few steps to fully manage all your projects, solution, MSBuild, VS IDE etc. 

Your choice ...  
*see MSDN and our docs.*

**Comment by dabalciunas** [comment]
Thanks for the fast reply! Well, I've followed the instructions: I have created a simple Console Application solution in VS2015 Community, added the pre-build event in VSBE, gave it a name and a caption, enabled it, unchecked 'Hide Process', selected 'Script Mode'. All SBE-Script components are enabled (I did not change these settings). Then I added this single line of code in the script textbox:

` #[Build cancel = true] `

Everything fine until now, but when I build the solution, I get the following error:

`[ERROR]: Pre-Build error: Command "Build.Cancel" is not available. vsSBE 0`

Which is not the error I was expecting to see in Visual Studio ;-)

For some strange reason `Build Cancel` is not available during the pre-build script. Am I still doing something wrong?

Thank you.

**Comment by 3F** [comment]
*oh yes, you need cancel build to first project...*
as I said above the `cancel` command will be executed **only if it's possible**, i.e. when this command will be available. You can check it manually: `Tools` - `Execution DTE-Commands` *btw, the `#[Build cancel = true]` breaks your build same as `#[DTE exec: Build.Cancel]` (all available see in Tools)*

The `Pre-Build` works before any build of your projects (**solution-context**), but the `cancel` can be executed only when the build is started at least for one.

So, **you need** use deferred Pre-Build or any other event type, for example:

* You can use `Execution order` list. Select all as `Before` type. Now the selected action should be as `deferred type` (if used Pre-Build / Cancel-Build / Post-Build event types), i.e. now it will be considered in **projects-context**.
* Or you can use `Transmitter` event type, or `Output-Build` and simple filter as 

```
started:*Project:` (Wildcards)
```
etc.

And of course for all this, you can wrap your actions with specific conditions like in my [example 1 above](https://github.com/3F/vsSolutionBuildEvent/issues/37#issuecomment-256664980).
