### ISSUE TITLE
Visual Studio 2019 supprt

### ISSUE THREAD

**Issue by elangelo** [3F/vsSolutionBuildEvent#44]
Any chance we might get this?

**Comment by 3F** [comment]
Sure. This is still my **active** project (today, this is still actively integrated with our other projects). 
Therefore, I have plans for VS2019 too.

Just no time for fast support. 
Anybody can also help to add some (#39)  support. I'll definitely review any PR.

Thanks for using and follow the news.

**Comment by elangelo** [comment]
I've been trying to get this to work on 2019 but i keep getting:
![image](https://user-images.githubusercontent.com/1935881/57230987-e4679e00-7019-11e9-92f1-86e3b1aa135a.png)

If i remember correctly on 2017 you got a yes/no button to still install it. Somehow that no longer works on 2019. I'll keep trying...
If you have any hints in what directions i should be looking that would be greatly appreciated.

**Comment by elangelo** [comment]
after closing and reopening visual studio my branch actually builds something that works for me. I don't want to create a PR for this because it's clearly not sufficient but maybe you could already have a look? 

https://github.com/elangelo/vsSolutionBuildEvent/commit/2c04d3f641a9a645e95f7b8c1616872df996cc81

**Comment by 3F** [comment]
@elangelo we're using VSIX manifest **[v1](https://docs.microsoft.com/ru-ru/previous-versions/dd393700(v=vs.100))** for support all products starting from **VS2010+.** But this is obsolete manifest after VS 15.0 (read #36)

**As for temp solution,** did you try to add partial support for 16.0 via the same `<VisualStudio Version="16.0">` record:
https://github.com/3F/vsSolutionBuildEvent/blob/e6f5f68fab83a145f71638e8600158996b3330a0/vsSolutionBuildEvent/source.extension.vsixmanifest#L44 

I can accept PR if it will work like for 15.0 (I did not check vsSBE for 16.0) . Please, only after real testing with latest RC VS2019.

I just mean, that for normal support we need to use VSIX **v3** :( This requires **separate distribution** for: 
```
VS2010, - v1
VS2012, - v1, (v2 - optional)
VS2013, - v1, (v2 - optional)
VS2015, - v1, (v2 - optional)
VS2017, - v3
VS2019. - v3
```

I have no priority to this for the coming months. Thus, you can try to add configuration for build both packages (v1 & v3 manifest) 

But anyway, most of changes was planned for this year. Some parts should be extracted into the new projects, some parts should be replaced by already existing:

* tools/msbuild replaced by https://github.com/3F/hMSBuild/  
*tools/msbuild.bat will not work with modern versions (15.0, 16.0) after major changes from MS for their products*
* sln/ isolated projects-engine replaced by https://github.com/3F/MvsSln it can fix some bugs like this: https://github.com/3F/vsSolutionBuildEvent/issues/42#issuecomment-489129521
* ...

**Comment by 3F** [comment]
Today, #45 finally initiates support of the modern 15+ products (n. VS2017 is 15, VS2019 is 16). 

Modern platform requires more than just update manifest file. I already added **AsyncPackages** implementation. So, basically we need to resolve some problems and add separate build of the both vsix packages. See the remaining subtasks there.

Welcome everyone to speed up the process, or please wait for my time.

**Comment by 3F** [comment]
We're fully ready for VS2019 and now completely integrated with *VS2017.

* For VS2017 will be also available old SDK10 package implementation like today's 0.12.10.10901. But SDK15 is recommended.

Other:

* Starting from VS2019 you need use only **SDK15** packages.
* VS2010, VS2012, VS2013, VS2015: **SDK10**
* CI /Build Servers, msbuild tools: **SDK10** or **SDK15**
* Devenv Command Line version: **SDK10**
* API: **SDK10** or **SDK15**

All binaries will be available from our GitHub Releases Page. (I've plane to migrate from sf for new publishing)

Everyone, please also test the last CI build before public release! 

Known problems here: https://github.com/3F/vsSolutionBuildEvent/pull/45
