### ISSUE TITLE
installer fails if Atmel studio is installed on computer

### ISSUE THREAD

**Issue by rezodlub** [3F/vsSolutionBuildEvent#60]
I have both Visual studio 2017 and Atmel Studio 7 installed. When I try to update vsSolutionBuildEvent I get an error that 'This extension is not installable on any currently installed products.' You can download Atmel studio from https://www.microchip.com/mplab/avr-support/atmel-studio-7 Installation log follows:

11. 12. 2019 13:58:48 - Microsoft VSIX Installer
11. 12. 2019 13:58:48 - -------------------------------------------
11. 12. 2019 13:58:49 - Initializing Install...
11. 12. 2019 13:58:49 - Extension Details...
11. 12. 2019 13:58:49 - 	Identifier      : 94ecd13f-15f3-4f51-9afd-17f0275c6266
11. 12. 2019 13:58:49 - 	Name            : vsSolutionBuildEvent
11. 12. 2019 13:58:49 - 	Author          : GitHub3F
11. 12. 2019 13:58:49 - 	Version         : 1.14.0
11. 12. 2019 13:58:49 - 	Description     : Event-Catcher with variety of advanced Actions to service projects, libraries, the build processes and processes at runtime from VisualStudio and MSBuild Tools.
11. 12. 2019 13:58:49 - 	Locale          : en-US
11. 12. 2019 13:58:49 - 	MoreInfoURL     : https://github.com/3F/vsSolutionBuildEvent
11. 12. 2019 13:58:49 - 	InstalledByMSI  : False
11. 12. 2019 13:58:49 - 	SupportedFrameworkVersionRange : [4.0,)
11. 12. 2019 13:58:49 - 
11. 12. 2019 13:58:49 - 	Supported Products : 
11. 12. 2019 13:58:49 - 		Microsoft.VisualStudio.Ultimate
11. 12. 2019 13:58:49 - 			Version : [10.0]
11. 12. 2019 13:58:49 - 		Microsoft.VisualStudio.Ultimate
11. 12. 2019 13:58:49 - 			Version : [11.0]
11. 12. 2019 13:58:49 - 		Microsoft.VisualStudio.Ultimate
11. 12. 2019 13:58:49 - 			Version : [12.0]
11. 12. 2019 13:58:49 - 		Microsoft.VisualStudio.Ultimate
11. 12. 2019 13:58:49 - 			Version : [14.0]
11. 12. 2019 13:58:49 - 		Microsoft.VisualStudio.Ultimate
11. 12. 2019 13:58:49 - 			Version : [15.0]
11. 12. 2019 13:58:49 - 		Microsoft.VisualStudio.Premium
11. 12. 2019 13:58:49 - 			Version : [10.0]
11. 12. 2019 13:58:49 - 		Microsoft.VisualStudio.Premium
11. 12. 2019 13:58:49 - 			Version : [11.0]
11. 12. 2019 13:58:49 - 		Microsoft.VisualStudio.Premium
11. 12. 2019 13:58:49 - 			Version : [12.0]
11. 12. 2019 13:58:49 - 		Microsoft.VisualStudio.Premium
11. 12. 2019 13:58:49 - 			Version : [14.0]
11. 12. 2019 13:58:49 - 		Microsoft.VisualStudio.Premium
11. 12. 2019 13:58:49 - 			Version : [15.0]
11. 12. 2019 13:58:49 - 		Microsoft.VisualStudio.Pro
11. 12. 2019 13:58:49 - 			Version : [10.0]
11. 12. 2019 13:58:49 - 		Microsoft.VisualStudio.Pro
11. 12. 2019 13:58:49 - 			Version : [11.0]
11. 12. 2019 13:58:49 - 		Microsoft.VisualStudio.Pro
11. 12. 2019 13:58:49 - 			Version : [12.0]
11. 12. 2019 13:58:49 - 		Microsoft.VisualStudio.Pro
11. 12. 2019 13:58:49 - 			Version : [14.0]
11. 12. 2019 13:58:49 - 		Microsoft.VisualStudio.Pro
11. 12. 2019 13:58:49 - 			Version : [15.0]
11. 12. 2019 13:58:49 - 		Microsoft.VisualStudio.IntegratedShell
11. 12. 2019 13:58:49 - 			Version : [10.0]
11. 12. 2019 13:58:49 - 		Microsoft.VisualStudio.IntegratedShell
11. 12. 2019 13:58:49 - 			Version : [11.0]
11. 12. 2019 13:58:49 - 		Microsoft.VisualStudio.IntegratedShell
11. 12. 2019 13:58:49 - 			Version : [12.0]
11. 12. 2019 13:58:49 - 		Microsoft.VisualStudio.IntegratedShell
11. 12. 2019 13:58:49 - 			Version : [14.0]
11. 12. 2019 13:58:49 - 		Microsoft.VisualStudio.IntegratedShell
11. 12. 2019 13:58:49 - 			Version : [15.0]
11. 12. 2019 13:58:49 - 		Microsoft.VisualStudio.Community
11. 12. 2019 13:58:49 - 			Version : [12.0]
11. 12. 2019 13:58:49 - 		Microsoft.VisualStudio.Community
11. 12. 2019 13:58:49 - 			Version : [14.0]
11. 12. 2019 13:58:49 - 		Microsoft.VisualStudio.Community
11. 12. 2019 13:58:49 - 			Version : [15.0]
11. 12. 2019 13:58:49 - 		Microsoft.VisualStudio.Enterprise
11. 12. 2019 13:58:49 - 			Version : [12.0]
11. 12. 2019 13:58:49 - 		Microsoft.VisualStudio.Enterprise
11. 12. 2019 13:58:49 - 			Version : [14.0]
11. 12. 2019 13:58:49 - 		Microsoft.VisualStudio.Enterprise
11. 12. 2019 13:58:49 - 			Version : [15.0]
11. 12. 2019 13:58:49 - 
11. 12. 2019 13:58:49 - 	References      : 
11. 12. 2019 13:58:49 - 		-------------------------------------------------------
11. 12. 2019 13:58:49 - 		Identifier   : Microsoft.VisualStudio.MPF
11. 12. 2019 13:58:49 - 		Name         : Visual Studio MPF
11. 12. 2019 13:58:49 - 		Version      : [10.0,)
11. 12. 2019 13:58:49 - 		MoreInfoURL  : 
11. 12. 2019 13:58:49 - 		Nested       : No
11. 12. 2019 13:58:49 - 
11. 12. 2019 13:58:49 - 
11. 12. 2019 13:58:49 - Searching for applicable products...
11. 12. 2019 13:58:49 - Found installed product - Global Location
11. 12. 2019 13:58:49 - Found installed product - AtmelStudio
11. 12. 2019 13:58:49 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by 3F** [comment]
@rezodlub, Did you try with SDK **15** packages? This is more like *SDK 10* package from your log above.

https://vssbe.r-eg.net/doc/Usage/#sdk10--sdk15-versions

```
Starting from VS2019 you need use only SDK15 packages.
VS2017: SDK10 or SDK15 (recommended)
```

Although SDK10 is available for VS2017, it will not provide full support as for the modern SDK15. 
Please check this out.

**Comment by rezodlub** [comment]
SDK15 doesn't help at all. Installer fails just the same. Logs below:

16. 12. 2019 09:55:49 - Microsoft VSIX Installer
16. 12. 2019 09:55:49 - -------------------------------------------
16. 12. 2019 09:55:50 - Initializing Install...
16. 12. 2019 09:55:50 - Extension Details...
16. 12. 2019 09:55:50 - 	Identifier      : 94ecd13f-15f3-4f51-9afd-17f0275c6266
16. 12. 2019 09:55:50 - 	Name            : vsSolutionBuildEvent
16. 12. 2019 09:55:50 - 	Author          : GitHub3F
16. 12. 2019 09:55:50 - 	Version         : 1.14.0
16. 12. 2019 09:55:50 - 	Description     : Event-Catcher with variety of advanced Actions to service projects, libraries, the build processes and processes at runtime from VisualStudio and MSBuild Tools.
16. 12. 2019 09:55:50 - 	Locale          : en-US
16. 12. 2019 09:55:50 - 	MoreInfoURL     : https://github.com/3F/vsSolutionBuildEvent
16. 12. 2019 09:55:50 - 	InstalledByMSI  : False
16. 12. 2019 09:55:50 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
16. 12. 2019 09:55:50 - 
16. 12. 2019 09:55:50 - 	Supported Products : 
16. 12. 2019 09:55:50 - 		Microsoft.VisualStudio.Pro
16. 12. 2019 09:55:50 - 			Version : [15.0,)
16. 12. 2019 09:55:50 - 		Microsoft.VisualStudio.Enterprise
16. 12. 2019 09:55:50 - 			Version : [15.0,)
16. 12. 2019 09:55:50 - 		Microsoft.VisualStudio.Community
16. 12. 2019 09:55:50 - 			Version : [15.0,)
16. 12. 2019 09:55:50 - 		Microsoft.VisualStudio.IntegratedShell
16. 12. 2019 09:55:50 - 			Version : [15.0,)
16. 12. 2019 09:55:50 - 		Microsoft.VisualStudio.VSWinExpress
16. 12. 2019 09:55:50 - 			Version : [15.0,)
16. 12. 2019 09:55:50 - 		Microsoft.VisualStudio.VWDExpress
16. 12. 2019 09:55:50 - 			Version : [15.0,)
16. 12. 2019 09:55:50 - 		Microsoft.VisualStudio.VSWinDesktopExpress
16. 12. 2019 09:55:50 - 			Version : [15.0,)
16. 12. 2019 09:55:50 - 
16. 12. 2019 09:55:50 - 	References      : 
16. 12. 2019 09:55:50 - 
16. 12. 2019 09:55:50 - Searching for applicable products...
16. 12. 2019 09:55:50 - Found installed product - Global Location
16. 12. 2019 09:55:50 - Found installed product - AtmelStudio
16. 12. 2019 09:55:50 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by 3F** [comment]
@rezodlub, I've just checked this problem via VM and clean installed VS2017 + Atmel Studio (as-installer-7.0.2389).

I confirm the problem. However, this is not relevant to our project at all.

Moreover, you can check it through other extensions, for example, the most popular:

* https://marketplace.visualstudio.com/items?itemName=SteveDowerMSFT.IndentGuides
* https://marketplace.visualstudio.com/items?itemName=SteveCadwallader.CodeMaid

All this will have the same issue: 

```
Searching for applicable products...
Found installed product - Global Location
Found installed product - AtmelStudio
VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
```


But, for example, the following will work:

* https://marketplace.visualstudio.com/items?itemName=GitHub.GitHubExtensionforVisualStudio

Because:

```xml
<Installation AllUsers="true" Experimental="false">
```

That triggers UAC.

That is, you need to contact with Atmel Studio support or with Microsoft support.


### Solution for this case

Try installing with administrator privileges, or even just like this:

```
VSIXInstaller vsSolutionBuildEvent.1.14.0.16ee135.SDK15.vsix
```

This is more like issue with paths to some dependencies after Atmel Studio installation that finally breaks VSIXInstaller.

Or try `VSIXInstaller /admin` if not.

The first command above (no admin) solved at least my problem in VM.

Let me know if you have any other questions. Thanks for using!

**Comment by rezodlub** [comment]
VSIXInstaller vsSolutionBuildEvent.1.14.0.16ee135.SDK15.vsix did the trick for me. Thank you.
