### ISSUE TITLE
Can't use MSBuild in Targets Mode

### ISSUE THREAD

**Issue by Rand-Random** [3F/vsSolutionBuildEvent#73]
I fail to write the following Soba script in Targets Mode

```
    #[var myBuildNumberFile = .version]
    #[( #[File exists.file("#[var myBuildNumberFile]")] ){ 
    }
    else{ 
    #[var myBuildNumber = 0]
    #[File write("#[var myBuildNumberFile]"):#[var myBuildNumber]]
    }]
    
    #[var myBuildNumber = #[File get("#[var myBuildNumberFile]")]]
    #[$(myBuildNumber = $([MSBuild]::Add($(myBuildNumber), 1)))]   
    #[File write("#[var myBuildNumberFile]"):#[var myBuildNumber]])]
```

because I keep getting the following message

> 19:57:39.7828 [ERROR]: [Post] error: Invalid static method invocation syntax: "[MSBuild]::Add(*Undefined*, *Undefined*)". Method '[MSBuild]::Add' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)). Check that all parameters are defined, are of the correct type, and are specified in the right order.

Here a simplified version

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

    <PropertyGroup>
        <MyFirstNumber>12</MyFirstNumber>
        <MySecondNumber>25</MySecondNumber>
    </PropertyGroup>

    <Target Name="Init">
        <Message Text ="The sum of @(MyFirstNumber) and @(MySecondNumber) is $([MSBuild]::Add($(MyFirstNumber), $(MySecondNumber)))" />
    </Target>
</Project>
```

Am I doing something wrong, or is there a bug in the usage MSBuild in Targets Mode?

**Comment by 3F** [comment]
You can increment [easier](https://vssbe.r-eg.net/doc/Scripts/MSBuild/#syntactic-sugar)

```java
$(myBuildNumber += 1)
```

Script also contains an incorrect block finalization, try like this:

```java
#[var myBuildNumberFile = .version]

#[(!#[File exists.file("$(myBuildNumberFile)")])
{
    #[var myBuildNumber = 0]
    #[File write("$(myBuildNumberFile)"):#[var myBuildNumber]]
}]

#[var myBuildNumber = #[File get("$(myBuildNumberFile)")]]
```

```java
#[$(myBuildNumber += 1)]   
#[File write("$(myBuildNumberFile)"):#[var myBuildNumber]]
```

You can debug it via *Settings* - *Tools* - *Testing tool*.


if not, using *Testing tool* What result for  

```java
= $([MSBuild]::Add(1, 1))
```

Thanks!

**Comment by 3F** [comment]
Oh, also, just noticed

> $([MSBuild]::Add($(MyFirstNumber), $(MySecondNumber)))

If you're trying to get the numbers from properties defined in targets mode, ie.

```xml
    <PropertyGroup>
        <MyFirstNumber>12</MyFirstNumber>
        <MySecondNumber>25</MySecondNumber>
    </PropertyGroup>
```

Then obviously need either uncheck option "*MSBuild support*" from the left control 
Or same define this variables as it was for *$(myBuildNumber)* somewhere - somehow.

SobaScript will work for targets mode too.
