### ISSUE TITLE
Visual Studio Setup Project error

### ISSUE THREAD

**Issue by tho-ma** [3F/vsSolutionBuildEvent#78]
Hi, 
I'm getting the following error building a solution with a visual studio setup project
The setup project is not build correctly, only a tmp file is generated.
With disabled vsssolutionbuildevent extension the setup project builds corrctly.

[ERROR]: Failed getting project from EnvDTE: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.  xxx.vdproj

[DEBUG]:    at Microsoft.Build.Shared.ProjectFileErrorUtilities.VerifyThrowInvalidProjectFile(Boolean condition, String errorSubCategoryResourceName, BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)
   at Microsoft.Build.Construction.ProjectRootElement.LoadDocument(String fullPath, Boolean preserveFormatting, Boolean loadAsReadOnly)

**Comment by 3F** [comment]
New version 1.16 now ignores vdproj legacy type because msbuild doesn't provide any support for this.

You can, however, discuss support for any legacy types here https://github.com/3F/MvsSln
