### ISSUE TITLE
Extension "Progress Telerik UI for WPF Extension" causes MSBuild properties to be *undefined*

### ISSUE THREAD

**Issue by Rand-Random** [3F/vsSolutionBuildEvent#80]
When I have the extension Progress Telerik UI for WPF Extension ( https://marketplace.visualstudio.com/items?itemName=TelerikInc.TelerikWPFVSExtensions ) enabled, the MSBuild Properties are undefined.

Here a screenshot of the issue:

![image](https://github.com/3F/vsSolutionBuildEvent/assets/9868626/22b644ff-16c8-45d7-b7f8-07f9ac52153a)

Thanks in advance, for taking your time.

**Comment by 3F** [comment]
Hello,

I have prepared a patch, #81. Tested on VS 17.9.6 and installed *Telerik.Windows.WPF.VSPackage.X64.vsix*
To be sure, please check these [artifacts](https://ci.appveyor.com/project/3Fs/vssolutionbuildevent/builds/49747363/artifacts) before merging.

**Comment by Rand-Random** [comment]
@3F 
Sorry about my late reply.
Got the message during my holiday and it totally slipped my mind. Sorry.

Can happily report it works like a charm. Thanks.

![image](https://github.com/3F/vsSolutionBuildEvent/assets/9868626/228f8d90-2239-4ef6-8ffe-43470c2de799)
![image](https://github.com/3F/vsSolutionBuildEvent/assets/9868626/627612d1-8b57-47be-b112-fa1168feb568)

**Comment by 3F** [comment]
@Rand-Random No problem. Thank you for your feedback!

Please note this is not a public release yet.
I'll try to prepare 1.16.1 this week. For #81 and other minor fixes and changes as it was mentioned earlier at https://mastodon.social/@github3F/112385246699027883
